export const GET_BREEDS = 'GET_BREEDS';
export const GET_BREEDS_BY_FILTER = 'GET_BREEDS_BY_FILTER';
export const GET_BREEDS_BY_TEMPS = 'GET_BREEDS_BY_FILTER';
export const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS';
export const POST_BREED = 'POST_BREED';